name: tests
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  default:
    name: default
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: list
        run: |
          ls -la
          pwd

  shellcheck:
    name: shellchecks
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      env:
        placeholder: test
    steps:
        - uses: actions/checkout@v2
        - name: Install deps
          run: |
            # Install deps
            apt update
            DEBIAN_FRONTEND=noninteractive apt install -y shellcheck
        - name: Shellcheck
          run: |
            shellcheck *.sh # Validating BASH